version: "3.7"
services:
    command_recognition:
        privileged: true
        image: nimashoghi/pocketsphinx
        volumes:
            - "./shared/models/command_recognition/:/model/"
            - "./shared/timelines/audio-timeline.json:/timeline.json"
            - "./shared/out/command_recognition/:/out/"
            - "./shared/start.txt:/start"
    random-computation:
        privileged: true
        image: nimashoghi/random-computation
        volumes:
            - "./shared/start.txt:/start"
            - "./shared/timelines/sign-timeline.json:/timeline.json"
    visual_slam:
        privileged: true
        image: nimashoghi/ubuntu-xenial-orb-slam2-apps:2-13-20
        command: slam_app /root/ORBvoc.txt MH01 mono http://172.18.0.1:8080/mono.yaml http://172.18.0.1:8080/stereo.yaml http://172.18.0.1:8080/mav0/cam0/data http://172.18.0.1:8080/mav0/cam1/data http://172.18.0.1:8080/timestamps.txt
        volumes:
            - "./shared/out/visual_slam/:/output/"
            - "./shared/start.txt:/start"
            - "./server.sock:/var/resource-allocator-ipc.sock"
